# Generated by Django 4.1.2 on 2022-12-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaspost',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='art'),
        ),
    ]
