# Generated by Django 4.1.2 on 2022-12-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_canvaspost_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvaspost',
            name='drawing',
            field=models.ImageField(upload_to='art'),
        ),
    ]
