# Generated by Django 4.1.2 on 2022-12-04 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_canvaslike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=120)),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.canvaspost')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
