# Generated by Django 4.1.2 on 2022-12-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_canvassuperlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasSuperlike',
        ),
    ]
