# Generated by Django 4.1.2 on 2022-12-13 17:57

import canvas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('c1', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c2', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c3', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c4', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c5', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c6', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c7', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c8', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c9', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c10', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c11', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
                ('c12', models.CharField(max_length=7, validators=[canvas.validators.hex_code_validator])),
            ],
        ),
    ]
