# Generated by Django 4.1.2 on 2022-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
