# Generated by Django 4.1.2 on 2022-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_alter_palette_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palette', models.IntegerField()),
            ],
        ),
    ]
