# Generated by Django 4.1.2 on 2022-11-21 00:26

from django.db import migrations, models
import userprofile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[userprofile.validators.validate_file_size]),
        ),
    ]
